"""empty message

Revision ID: f49d94bb5933
Revises: 2017c4ed3390
Create Date: 2019-03-09 16:08:59.848955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49d94bb5933'
down_revision = '2017c4ed3390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('avatar', sa.Unicode(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'avatar')
    # ### end Alembic commands ###
